version: '3.7'

services:

  admin-prod:
    container_name: admin-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    # image: gonzalokonatech/admin:latest
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - '3001:3000'
    command: nginx -g "daemon off;"
    network_mode: bridge
    external_links:
    - pdi-slave:pdi
    - postgreststarterkit_postgrest_1:postgrest
    - docsify_docsify_1:docsify
    - filestash:filestash