version: '3.7'

services:

  admin:
    container_name: admin
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: gonzalokonatech/admin:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:80'
    command: npm start
    network_mode: bridge
    external_links:
    - bi:bi
    - postgreststarterkit_postgrest_1:postgrest
    - docsify_docsify_1:docsify
    - filestash:filestash
    labels:
    - traefik.backend=admin
    - traefik.frontend.rule=Host:admin.bieccamvd.com
    - traefik.docker.network=bridge
    - traefik.port=80