version: '3.7'

services:

  admin-prod:
    container_name: admin-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    # image: gonzalokonatech/admin:latest
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - '3001:80'
    command: nginx -g "daemon off;"
    network_mode: bridge
    external_links:
    - bi:bi
    - postgreststarterkit_postgrest_1:postgrest
    - docsify_docsify_1:docsify
    - filestash:filestash
    labels:
    - traefik.backend=admin
    - traefik.frontend.rule=Host:admin.bieccamvd.com
    - traefik.docker.network=bridge
    - traefik.port=80