version: '3.7'

services:

  admin:
    image: gonzalokonatech/admin:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    command: npm start